# Generated by Django 4.2.7 on 2025-07-14 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for the target system', max_length=255)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the target system')),
                ('hostname', models.CharField(blank=True, help_text='Hostname of the target system', max_length=255, null=True)),
                ('operating_system', models.CharField(choices=[('windows', 'Windows'), ('linux', 'Linux'), ('unix', 'Unix')], help_text='Operating system type', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('name', 'ip_address')},
            },
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Session name', max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('target_systems', models.ManyToManyField(related_name='test_sessions', to='va_core.targetsystem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CredentialTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Username for authentication', max_length=255)),
                ('auth_method', models.CharField(choices=[('password', 'Username/Password'), ('ssh_key', 'SSH Key'), ('kerberos', 'Kerberos'), ('ntlm', 'NTLM')], default='password', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('unauthorized', 'Unauthorized'), ('connection_error', 'Connection Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('test_output', models.JSONField(default=dict, help_text='Detailed test output (excluding sensitive data)')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credential_tests', to='va_core.targetsystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectivityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(default='ping', help_text='Type of connectivity test (ping, port_scan, etc.)', max_length=50)),
                ('port', models.IntegerField(blank=True, help_text='Port number for port-specific tests', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('test_output', models.JSONField(default=dict, help_text='Detailed test output')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_tests', to='va_core.targetsystem')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
