# Generated by Django 4.2.7 on 2025-07-14 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('va_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(help_text='Unique identifier for the bulk scan', max_length=100, unique=True)),
                ('ip_input', models.TextField(help_text='Original IP input string')),
                ('total_ips', models.IntegerField(help_text='Total number of IPs scanned')),
                ('successful_scans', models.IntegerField(default=0, help_text='Number of successful IP scans')),
                ('failed_scans', models.IntegerField(default=0, help_text='Number of failed IP scans')),
                ('error_scans', models.IntegerField(default=0, help_text='Number of error IP scans')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('timeout_setting', models.IntegerField(default=5, help_text='Timeout setting used for the scan')),
                ('system_types', models.JSONField(default=dict, help_text='Summary of detected system types')),
                ('scan_results', models.JSONField(default=list, help_text='Detailed scan results for each IP')),
                ('created_systems', models.IntegerField(default=0, help_text='Number of target systems created')),
                ('saved_tests', models.IntegerField(default=0, help_text='Number of individual tests saved')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='connectivitytest',
            name='bulk_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectivity_tests', to='va_core.bulkscan'),
        ),
    ]
