# Generated by Django 4.2.7 on 2025-07-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('va_core', '0002_bulkscan_connectivitytest_bulk_scan'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkscan',
            name='name',
            field=models.CharField(default='Bulk Scan', help_text='Custom name for the bulk scan (e.g., project name)', max_length=255),
        ),
    ]
